# Generated by Django 5.2 on 2025-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='session id'),
        ),
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='url'),
        ),
    ]
