# Generated by Django 5.2 on 2025-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
